var GAME_LEVELS = [
  ["                                                                               ",
  "                                                                                ",
  "                                                                                ",
  "                                                                                ",
  "                                                                                ",
  "                                                                                ",
  "            o                                                                   ",
  "      xxxxxxxxxxxxxx                                              xxxxx         ",
  "    xxxssssssx!!!!!x                                  xx          xx!xx         ",
  "   xxxs    xxx!!!!!xxx                                ss          xx!xx         ",
  "           x!!!!!!xxx      xxx                                    !!!           ",
  "x          xx!!!!!xx        xxx       xxxxx             pp       !!xvvxx     o  ",
  "xx          x!!x!!xx                                          !!!!v         xxxx",
  "xxx  yyy    x!!!!xx                       yyyyy              !!!!!              ",
  "xxxx        x!!xxx                 xxx                  yyyy x!  v      yy      ",
  "xxxx             xxxxxxx                        yy                       xxxx  x",
  "xx                                                                             x",
  "x                                         ssss                                  ",
  "x  xx    x       xxxx                    xxxxx                                ox",
  "x       xxx  y     xxx           yyy                                         xxx",
  "x@  o xxxxx     oxxx                                           xxxxxx       xxx ",
  "xxxxxxxxxxx!xx!xxxxxxxxxxxxx!!!xx!!!!xxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxx",
  "          x!!!!x           x!!!!!!!!!x     xxxxxxxx     xxxx                    ",
  "          x!!!!x           x!!!!!!!!!x     x         x!!!!!x                    ",
  "          x!!!!x           x!!!!!!!!!x     xo       xx!!!!!x                    ",
  "          xxxxxx           xxxxxxxxxxx     xxxxx     x!!!!!x                    ",
  "                                              xxxxxxxxxxxxxx                    ",
  "                                                                                ",
  "                                                                                "],
  ["x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x                                                                                                                 ",
     "x     pp      x           pppp                           xx                xxx         xxxxxxxxx                  ",
     "x           xxxx                               xxxxxxx    xx               xx          xxx                        ",
     "x             xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  || x    xx              xx          xx                          ",
     "x             xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x    x              xx          xx                           ",
     "xxxxxx        xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x     x   ss             xx          xx                            ",
     "x             xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    x   ss            xx         xxx                             ",
     "x             xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    xx   ss                      xx                               ",
     "x         xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    xx  sss       p            xxx                                ",
     "x             xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    xx sss     o             xxx                                 ",
     "x@            xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx    xxxxsssxxxxxsssssssssssxxxxxxxxxxxxx                        ",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            ",
     "xxxxxxxxx                                                                      |                                  ",
     "x       x          =    |                          uu                                                             ",
     "x     o x                                                             |                                           ",
     "x   xxxxx     |                                       yyy                                                         ",
     "xo       |          =    |                                                                                        ",
     "xxx                                                         yy           |                                        ",
     "x                           =        x                                                                            ",
     "x            =                       x                =                                  x                        ",
     "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                          x                                                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxss                                   ",
   "                                          x                              xss                                  ",
   "                                          x                               xssssss                             ",
   "                                          x                                xxxxxx                             ",
   "                                          x                                                                   ",
   "                                          x                                                                   ",
   "                                          x                                                                   ",
   "x                               xxxxxxs   x                             xxx       x!!!x         xxx          x",
   "x                              xx!!!!!xs  x                             x+x        xxx         x   x         x",
   "x                             xx!!!!!!!x  x            x o  x    x  o  x++xx                  xs   sx        x",
   "x                             xx!!!!!!!! ux!!x    x!!!!x    x!!!!x    xx+++xx                xs     sx       x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!v  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx+++++xxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxxx",
   "x                       sssss   vvvvvvvv                               zzzzzz   |           x!!!!!!!!!!!!!!!!x",
   "x                            =|                                       ******                x!!!!!!!!!!!!!!!!x",
   "x        u                                |                                               | x!!!!!!!!!!!!!!!!x",
   "x               |                                                     ******         |      x!!!!!!!!!!!!!!!!x",
   "x                                                                                           x!!!!!!!!!!!!!!!!x",
   "x                                           |                                               x!!!!!!!!!!!!!!!!x",
   "x      pp               x                    x                     pp                       x!!!!!!!!!!!!!!!!x",
   "x                                                                               |           x!!!!!!!!!!!!!!!!x",
   "xyyy              =          y                                                         |    x!!!!!!!!!!!!!!!!x",
   "x                            y            =                                                 x!!!!!!!!!!!!!!!!x",
   "x@    o                   = uy      =              sssssssssssssssssssssssssssssssssssssssssx!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                         ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                           ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx o                                                                          ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx                                                                              ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                                 ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                                                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!xxx                                                                                   ",
   "!!!!!!!!!!!!!!!!!!!!!!xxx                                                                                      ",
   "!!!!!!!!!!!!!!!!!!!!xxx                                                                                        ",
   "!!!!!!!!!!!!!!xxxxxxx                                                                                          ",
   "!!!!!!!!!!!!!xxx                                                                                               ",
   "!!!!!!!!!!!xxx                                                                                                 ",
   "!!!!!!!!!xxx                                                                                                   ",
   "!!!!!!!xxx                                                                                                     ",
   "!!!!!xxx                                                                                                       ",
   "!!!xxx                                                                                                         ",
   "!xxx                                                                                                           ",
   "!x                                                                                                             ",
   "!x                                                                                                             ",
   "!x                                                                                                             ",
   "!x                   sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss                   ",
   "!x                                                                                                             ",
   "!x                                                               ||                                            ",
   "!x                                                                                                             ",
   "!x                              x    x    xx     x  o   xx    xxxxx  xxxxx                                     ",
   "!x                           yy x    x     xx   xxx   xx       x    xx xx                                      ",
   "!x!!   o                        x    x      xx xx xx xx        xo   xx xx                                      ",
   "!!!!!@    pp                    xxxxxx       xxx   xxx       xxxxx  xx xx                                      ",
   "!!!!!x        x         yy                                                                                     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
